### ISSUE TITLE
Every day the app stops in docker container.

### ISSUE THREAD

**Issue by SpoturDeal** [robertklep/onvif2mqtt#1]
Hello,

I am very happy with your app. Finally, I am able to detect persons in front of my house. (Reolink RLC-822A camera)

I have the app running in a docker container on my Synology NAS.

About twice a day, the app stops (and is restarted in the container) with the following error message in the log.

```
ONVIF2MQTT
date,stream,content
2023/10/09 09:15:21,stderr,Node.js v19.9.0
2023/10/09 09:15:21,stderr,
2023/10/09 09:15:21,stderr,    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
2023/10/09 09:15:21,stderr,    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
2023/10/09 09:15:21,stderr,    at emitErrorNT (node:internal/streams/destroy:151:8)
2023/10/09 09:15:21,stderr,    at Socket.emit (node:events:513:28)
2023/10/09 09:15:21,stderr,    at Socket.socketErrorListener (node:_http_client:495:9)
2023/10/09 09:15:21,stderr,    at ClientRequest.emit (node:events:513:28)
2023/10/09 09:15:21,stderr,    at ClientRequest.<anonymous> (/app/node_modules/onvif/lib/cam.js:328:4)
2023/10/09 09:15:21,stderr,    at Cam.<anonymous> (/app/node_modules/onvif/lib/events.js:309:14)
2023/10/09 09:15:21,stderr,TypeError: callback.call is not a function
2023/10/09 09:15:21,stderr,
2023/10/9 09:15:21,stderr,				         ^
2023/10/09 09:15:21,stderr,"				callback.call(this, err, data, xml);
"
2023/10/09 09:15:21,stderr,/app/node_modules/onvif/lib/events.js:309
```

Is someone else having this problem?

**Comment by robertklep** [comment]
I don't have this issue myself, but I noticed there's a new version of the `onvif` module available that might be causing it.

In the `package.json` file, replace this line:
```
"onvif": "^0.6.8",
```
with this:
```
"onvif": "0.6.8",
```

Then rebuild the Docker image (`docker-compose build`) and start a new container (`docker-compose up -d`).

**Comment by SpoturDeal** [comment]
I have removed the ^ within the package.json, now wait and cross my fingers.
Let you know in a few days.

**Comment by SpoturDeal** [comment]
After making the change in the package.json the error is still there.
It doesn't seem to be a bug in the app. It always occurs at the same time, 09:15 in the morning.

So now checking my camera's and network.

**Comment by robertklep** [comment]
Do you restart your cameras perhaps?

I restart mine daily, and I just noticed that when they restart, `onvif2mqtt` does handle the restart correctly (in that it doesn't crash), but it stops receiving ONVIF events. It's not the same issue that you're having, but still worth a mention.

FWIW, one of the reasons I do a daily reboot is that I found Reolinks ONVIF implementation to be unstable, at some point the camera just seems to stop sending motion events over ONVIF. For me, the Home Assistant integration works well enough now to not have to rely on `onvif2mqtt` so much.

**Comment by SpoturDeal** [comment]
Hello Robert,

Just found the cause. The camera had auto-restart activated. Just disabled it. My camera doesn't have the unstable motion events.

I am using it with OpenHAB it is not a security function but more a privacy thing. Some people that walk up to the front door, walk up to the kitchen window to look inside. Now, if a person walks up to the door, the roller curtain is lowered.

Many thanks for your help and advice.

**Comment by robertklep** [comment]
Good to know your problem was solved 😊
